# Jekyll configuration

name: Pavel Makhov
description: Software Developer

url: http://streetturtle.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl:

social:
  github: streetturtle
  stackoverflow: streetturtle
  linkedin: streetturtle
  codepen: streetturtle
  instagram: streetturtle
  lastfm: streetturtle
  rss: feed.xml

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest:
  email: true

collections:
  quicknotes:
    output: true

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-57641651-1
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrika: true

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: streetturtle
comments: true

permalink: /:year/:month/:title
gems: [jekyll-paginate]
paginate: 10

#highlighter: rouge
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

exclude: ['README.md', 'LICENSE', vendor]
